export const TOKENS = {
  config: Symbol('config'),
  database: Symbol('database'),
  pool: Symbol('pool'),
  identityRepository: Symbol('identityRepository'),
  leadRepository: Symbol('leadRepository'),
  opportunityRepository: Symbol('opportunityRepository'),
  productRepository: Symbol('productRepository'),
  configurationRepository: Symbol('configurationRepository'),
  createLeadService: Symbol('createLeadService'),
  readLeadService: Symbol('readLeadService'),
  createOpportunityService: Symbol('createOpportunityService'),
  readOpportunityService: Symbol('readOpportunityService'),
  readCatalogService: Symbol('readCatalogService'),
  createConfigurationService: Symbol('createConfigurationService'),
  reviseConfigurationService: Symbol('reviseConfigurationService'),
  readConfigurationService: Symbol('readConfigurationService'),
} as const;
